// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3JaQyBGdw9t4vOP5mXn_ILpuVPmQWo0',
    appId: '1:605933927192:web:9048193d1ccf1ad1ed7c6d',
    messagingSenderId: '605933927192',
    projectId: 'projectecho-d3e34',
    authDomain: 'projectecho-d3e34.firebaseapp.com',
    storageBucket: 'projectecho-d3e34.firebasestorage.app',
    measurementId: 'G-K7P7L3WHPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATo2oOhkJl3QZRj5oZ5WrdY7PgUWRbvqw',
    appId: '1:605933927192:android:0d32a60427a7484fed7c6d',
    messagingSenderId: '605933927192',
    projectId: 'projectecho-d3e34',
    storageBucket: 'projectecho-d3e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbzvUzp6z-Wg0fH8pPu8stQCRgo8kMYns',
    appId: '1:605933927192:ios:363eaeb49edb976fed7c6d',
    messagingSenderId: '605933927192',
    projectId: 'projectecho-d3e34',
    storageBucket: 'projectecho-d3e34.firebasestorage.app',
    iosBundleId: 'com.example.projecho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbzvUzp6z-Wg0fH8pPu8stQCRgo8kMYns',
    appId: '1:605933927192:ios:363eaeb49edb976fed7c6d',
    messagingSenderId: '605933927192',
    projectId: 'projectecho-d3e34',
    storageBucket: 'projectecho-d3e34.firebasestorage.app',
    iosBundleId: 'com.example.projecho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf3JaQyBGdw9t4vOP5mXn_ILpuVPmQWo0',
    appId: '1:605933927192:web:7248ab4f3e247fb0ed7c6d',
    messagingSenderId: '605933927192',
    projectId: 'projectecho-d3e34',
    authDomain: 'projectecho-d3e34.firebaseapp.com',
    storageBucket: 'projectecho-d3e34.firebasestorage.app',
    measurementId: 'G-GYCM8GCCBQ',
  );

}